name: cifar10_trial_dsat_fake_data
workspace: DS_AT_PROTOTYPING
project: cifar10
debug: false
hyperparameters:
  deepspeed_config: ds_config.json
  # ds_config:
  #   autotuning:
  #     enabled: True
  #     fast: False
  #     tuner_type: random
  #     tuner_num_trials: 50
  #     num_tuning_micro_batch_sizes: 5
  #     tuner_early_stopping: 5
  #     metric: throughput
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    # You may need to modify this to match your network configuration.
    - NCCL_SOCKET_IFNAME=ens,eth,ib
  #    - CUDA_LAUNCH_BLOCKING=1
  #    - NCCL_BLOCKING_WAIT=1
  #    - NCCL_IB_DISABLE=1
  image:
    gpu: determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-deepspeed-0.7.0-gpu-0e4beb5
bind_mounts:
  - host_path: /tmp
    container_path: /data
  - host_path: /tmp
    container_path: /root/.cache
resources:
  slots_per_trial: 2
  shm_size: 17179869184 # 16 GiB. Was hitting "Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)." on Grenoble.
searcher:
  name: custom
  metric: throughput
  smaller_is_better: false
entrypoint:
  - python3
  - -m
  - determined.launch.deepspeed
  - --trial
  - model_def:CIFARTrial
checkpoint_policy: none
max_restarts: 0
scheduling_unit: 2000
